;; -*- coding: ctext; -*-

(defvar rail-flim-codename-alist
  '((#("Tōji" 0 1 (charset japanese-jisx0208) 1 4 (charset latin-iso8859-4)) . "東寺")
    ("Kamitobaguchi"      . "上鳥羽口")
    ("Fushimi"            . "伏見")
    ("Kintetsu-Tambabashi" . "近鉄丹波橋")
    (#("Momoyama-Goryōmae" 0 13 (charset japanese-jisx0208) 13 17 (charset latin-iso8859-4)) . "桃山御陵前")
    ("Mukaijima"          . "向島")
    ("Ogura"              . "小倉")
    ("Iseda"              . "伊勢田")
    (#("Ōkubo" 0 5 (charset latin-iso8859-4)) . "大久保")
    ("Kutsukawa"          . "久津川")
    ("Terada"             . "寺田")
    (#("Tonoshō" 0 6 (charset japanese-jisx0208) 6 7 (charset latin-iso8859-4)) . "富野荘")
    ("Shin-Tanabe"        . "新田辺")
    (#("Kōdo" 0 1 (charset japanese-jisx0208) 1 4 (charset latin-iso8859-4)) . "興戸")
    ("Miyamaki"           . "三山木")
    ("Kintetsu-Miyazu"    . "近鉄宮津")
    ("Komada"             . "狛田")
    (#("Shin-Hōsono" 0 6 (charset japanese-jisx0208) 6 11 (charset latin-iso8859-4)) . "新祝園")
    ("Kizugawadai"        . "木津川台")
    ("Yamadagawa"         . "山田川")
    ("Takanohara"         . "高の原")
    (#("Heijō" 0 4 (charset japanese-jisx0208) 4 5 (charset latin-iso8859-4)) . "平城")
    ("Saidaiji"           . "西大寺")
    ("Amagatsuji"         . "尼ヶ辻")
    (#("Nishinokyō" 0 9 (charset japanese-jisx0208) 9 10 (charset latin-iso8859-4)) . "西の京")
    (#("Kintetsu-Kōriyama" 0 10 (charset japanese-jisx0208) 10 17 (charset latin-iso8859-4)) . "近鉄郡山")
    ("Tsutsui"            . "筒井")
    (#("Family-Kōenmae" 0 8 (charset japanese-jisx0208) 8 14 (charset latin-iso8859-4)) . "ファミリー公園前")
    (#("Yūzaki" 0 1 (charset japanese-jisx0208) 1 6 (charset latin-iso8859-4)) . "結崎")
    ("Iwami"              . "石見")
    ("Tawaramoto"         . "田原本")
    ("Kasanui"            . "笠縫")
    ("Ninokuchi"          . "新ノ口")
    ("Yagi"               . "八木")
    ("Yagi-Nishiguchi"    . "八木西口")
    (#("Unebigoryōmae" 0 9 (charset japanese-jisx0208) 9 13 (charset latin-iso8859-4)) . "畝傍御陵前")
    ("Kashiharajingu-mae" . "橿原神宮前")
    ("Demachiyanagi"      . "出町柳")
    ("Marutamachi"        . "丸太町")
    (#("Sanjō" 0 4 (charset japanese-jisx0208) 4 5 (charset latin-iso8859-4)) . "三条")
    (#("Shichijō" 0 7 (charset japanese-jisx0208) 7 8 (charset latin-iso8859-4)) . "七条")
    (#("Tobakaidō" 0 8 (charset japanese-jisx0208) 8 9 (charset latin-iso8859-4)) . "鳥羽街道")
    ("Fushimiinari"       . "伏見稲荷")
    ("Fukakusa"           . "深草")
    ("Fujinomori"         . "藤森")
    ("Sumizome"           . "墨染")
    ("Tambabashi"         . "丹波橋")
    ("Fushimimomoyama"    . "伏見桃山")
    (#("Chūshojima" 0 2 (charset japanese-jisx0208) 2 10 (charset latin-iso8859-4)) . "中書島")
    ("Yodo"               . "淀")
    ("Yawatashi"          . "八幡市")
    ("Hashimoto"          . "橋本")
    ("Kuzuha"             . "樟葉")
    ("Makino"             . "牧野")
    ("Goten-yama"         . "御殿山")
    ("Hirakatashi"        . "枚方市")
    (#("Hirakatakōen" 0 9 (charset japanese-jisx0208) 9 12 (charset latin-iso8859-4)) . "枚方公園")
    (#("Kōzenji" 0 1 (charset japanese-jisx0208) 1 7 (charset latin-iso8859-4)) . "光善寺")
    (#("Kōrien" 0 1 (charset japanese-jisx0208) 1 6 (charset latin-iso8859-4)) . "香里園")
    ("Neyagawashi"        . "寝屋川市")
    ("Kayashima"          . "萱島")
    (#("Ōwada" 0 5 (charset latin-iso8859-4)) . "大和田")
    ("Furukawabashi"      . "古川橋")
    ("Kadomashi"          . "門真市")
    (#("Nishisansō" 0 9 (charset japanese-jisx0208) 9 10 (charset latin-iso8859-4)) . "西三荘")
    ("Moriguchishi"       . "守口市")
    ("Doi"                . "土居")
    ("Takii"              . "滝井")
    ("Sembayashi"         . "千林")
    (#("Morishōji" 0 6 (charset japanese-jisx0208) 6 9 (charset latin-iso8859-4)) . "森小路")
    ("Sekime"             . "関目")
    ("Noe"                . "野江")
    (#("Kyōbashi" 0 2 (charset japanese-jisx0208) 2 8 (charset latin-iso8859-4)) . "京橋")
    ("Temmabashi"         . "天満橋")
    ("Kitahama"           . "北浜")
    ("Yodoyabashi"        . "淀屋橋")
    ("Takeda"             . "竹田")
    ("Kuinabashi"         . "くいな橋")
    (#("Jūjō" 0 1 (charset japanese-jisx0208) 1 4 (charset latin-iso8859-4)) . "十条")
    (#("Kujō" 0 3 (charset japanese-jisx0208) 3 4 (charset latin-iso8859-4)) . "九条")
    (#("Kyōto" 0 2 (charset japanese-jisx0208) 2 5 (charset latin-iso8859-4)) . "京都")
    (#("Gojō" 0 3 (charset japanese-jisx0208) 3 4 (charset latin-iso8859-4)) . "五条")
    (#("Shijō" 0 4 (charset japanese-jisx0208) 4 5 (charset latin-iso8859-4)) . "四条")
    ("Karasuma Oike"      . "烏丸御池")
    ("Marutamach"         . "丸太町")
    ("Imadegawa"          . "今出川")
    ("Kuramaguchi"        . "鞍馬口")
    (#("Kitaōji" 0 4 (charset japanese-jisx0208) 4 7 (charset latin-iso8859-4)) . "北大路")
    ("Kitayama"           . "北山")
    ("Matugasaki"         . "松ヶ崎")
    ("Kokusaikaikan"      . "国際会館")
    (#("[JR] Kyōto" 0 7 (charset japanese-jisx0208) 7 10 (charset latin-iso8859-4)) . "京都")
    (#("Tōfukuji" 0 1 (charset japanese-jisx0208) 1 8 (charset latin-iso8859-4)) . "東福寺")
    ("Inari"              . "稲荷")
    ("JR Fujinomori "     . "JR 藤森")
    ("Momoyama"           . "桃山")
    (#("Rokujizō" 0 7 (charset japanese-jisx0208) 7 8 (charset latin-iso8859-4)) . "六地蔵")
    ("Kohata"             . "木幡")
    (#("Ōbaku" 0 5 (charset latin-iso8859-4)) . "黄檗")
    ("Uji"                . "宇治")
    ("Shinden"            . "新田")
    (#("Jōyō" 0 1 (charset japanese-jisx0208) 1 4 (charset latin-iso8859-4)) . "城陽")
    ("Nagaike"            . "長池")
    ("Yamashiro-Aodani"   . "山城青谷")
    ("Yamashiro-Taga"     . "山城多賀")
    ("Tamamizu"           . "玉水")
    ("Tanakura"           . "棚倉")
    ("Kamikoma"           . "上狛")
    ("Kidu"               . "木津")
    (#("Shin-Hōryūji" 0 6 (charset japanese-jisx0208) 6 12 (charset latin-iso8859-4)) . "新法隆寺")
    ("Ando"               . "安堵")
    ("Nukatabe"           . "額田部")
    ("Hirahata"           . "平端")
    ("Shin-Terai"         . "新寺井")
    ("Tameike"            . "溜池")
    ("Kaga-Fukuoka"       . "加賀福岡")
    (#("Nakanoshō" 0 8 (charset japanese-jisx0208) 8 9 (charset latin-iso8859-4)) . "中ノ庄")
    (#("Gokendō" 0 6 (charset japanese-jisx0208) 6 7 (charset latin-iso8859-4)) . "五間堂")
    ("Terai-Nishiguchi"   . "寺井西口")
    (#("Jidōsha-Renraku" 0 3 (charset japanese-jisx0208) 3 15 (charset latin-iso8859-4)) . "自動車連絡")
    ("Hon-Terai"          . "本寺井")
    ("Suenobuushijima"    . "末信牛島")
    ("Kaga-Sano"          . "加賀佐野")
    ("Yunotani-Ishiko"    . "湯谷石子")
    ("Tokuhisa"           . "徳久")
    ("Kami-Kaihatsu"      . "上開発")
    ("Tatsunokuchi"       . "辰口")
    ("Raimaru"            . "来丸")
    ("Higama"             . "火釜")
    ("Iwauchi"            . "岩内")
    ("Mitsukuchi"         . "三口")
    ("Miyatake"           . "宮竹")
    ("Todashino"          . "灯台笹")
    ("Iwamoto"            . "岩本")
    ("Tenguyama"          . "天狗山")
    ("Hon-Tsurugi"        . "本鶴来")
    ("Tsurugi"            . "鶴来")
    (#("Ōsaka-Abenobashi" 0 16 (charset latin-iso8859-4)) . "大阪阿部野橋")
    ("Koboreguchi"        . "河堀口")
    ("Kita-tanabe"        . "北田辺")
    ("Imagawa"            . "今川")
    ("Harinakano"         . "針中野")
    ("Yata"               . "矢田")
    ("Kawachi-Amami"      . "河内天美")
    ("Nunose"             . "布忍")
    ("Takaminosato"       . "高見ノ里")
    ("Kawachi-Matsubara"  . "河内松原")
    (#("Eganoshō" 0 7 (charset japanese-jisx0208) 7 8 (charset latin-iso8859-4)) . "恵我ノ荘")
    ("Takawashi"          . "高鷲")
    ("Fujiidera"          . "藤井寺")
    ("Hajinosato"         . "土師の里")
    (#("Dōmyōji" 0 1 (charset japanese-jisx0208) 1 7 (charset latin-iso8859-4)) . "道明寺")
    ("Furuichi"           . "古市")
    ("Komagatani"         . "駒ヶ谷")
    ("Kaminotaishi"       . "上ノ太子")
    (#("Nijōsan" 0 3 (charset japanese-jisx0208) 3 7 (charset latin-iso8859-4)) . "二上山")
    (#("Nijōjinjaguchi" 0 3 (charset japanese-jisx0208) 3 14 (charset latin-iso8859-4)) . "二上神社口")
    ("Taimadera"          . "当麻寺")
    ("Iwaki"              . "磐城")
    ("Shakudo"            . "尺土")
    ("Takadashi"          . "高田市")
    ("Ukiana"             . "浮孔")
    (#("Bōjō" 0 1 (charset japanese-jisx0208) 1 4 (charset latin-iso8859-4)) . "坊城")
    (#("Kashiharajingū-Nisiguchi" 0 13 (charset japanese-jisx0208) 13 24 (charset latin-iso8859-4)) . "橿原神宮西口")
    (#("Kashiharajingūmae" 0 13 (charset japanese-jisx0208) 13 17 (charset latin-iso8859-4)) . "橿原神宮前")
    ("Okadera"            . "岡寺")
    ("Asuka"              . "飛鳥")
    ("Tsubosakayama"      . "壺阪山")
    ("Ichio"              . "市尾")
    ("Kuzu"               . "葛")
    ("Yoshinoguchi"       . "吉野口")
    ("Kusurimizu"         . "薬水")
    ("Fukugami"           . "福神")
    (#("Ōada" 0 4 (charset latin-iso8859-4)) . "大阿太")
    ("Shimoichiguchi"     . "下市口")
    ("Koshibe"            . "越部")
    ("Muda"               . "六田")
    ("Yamato-Kamiichi"    . "大和上市")
    (#("Yoshinojingū" 0 11 (charset japanese-jisx0208) 11 12 (charset latin-iso8859-4)) . "吉野神宮")
    ("Yoshino"            . "吉野")))

(provide 'rail-table-flim)
