;; -*- coding: ctext; -*-

(defvar rail-semi-codename-alist
  '(("Kaga-Ichinomiya"    . "加賀一の宮")
    ("Naka-Tsurugi"       . "中鶴来")
    ("Tsurugi"            . "鶴来")
    ("Hinomiko"           . "日御子")
    ("Oyanagi"            . "小柳")
    ("Inokuchi"           . "井口")
    (#("Dōhōji" 0 1 (charset japanese-jisx0208) 1 6 (charset latin-iso8859-4)) . "道法寺")
    ("Sodani"             . "曽谷")
    ("Shijima"            . "四十万")
    ("Otomaru"            . "乙丸")
    (#("Nukajūtaku-mae" 0 5 (charset japanese-jisx0208) 5 14 (charset latin-iso8859-4)) . "額住宅前")
    ("Magae"              . "馬替")
    (#("Nonoichi-Kōdaimae" 0 10 (charset japanese-jisx0208) 10 17 (charset latin-iso8859-4)) . "野々市工大前")
    ("Nonoichi"           . "野々市")
    ("Oshino"             . "押野")
    ("Shin-Nishikanazawa" . "新西金沢")
    ("Nishiizumi"         . "西泉")
    ("Nomachi"            . "野町")
    ("Naoetsu"            . "直江津")
    ("Tanihama"           . "谷浜")
    ("Arimagawa"          . "有間川")
    ("Nadachi"            . "名立")
    ("Tsutsuishi"         . "筒石")
    (#("Nō" 0 1 (charset japanese-jisx0208) 1 2 (charset latin-iso8859-4)) . "能生")
    ("Uramoto"            . "浦本")
    ("Kajiyashiki"        . "梶屋敷")
    ("Itoigawa"           . "糸魚川")
    (#("Ōmi" 0 3 (charset latin-iso8859-4)) . "青海")
    ("Oyashirazu"         . "親不知")
    ("Ichiburi"           . "市振")
    (#("Ecchū-Miyazaki" 0 4 (charset japanese-jisx0208) 4 14 (charset latin-iso8859-4)) . "越中宮崎")
    ("Tomari"             . "泊")
    (#("Nyūzen" 0 2 (charset japanese-jisx0208) 2 6 (charset latin-iso8859-4)) . "入善")
    (#("Nishi-Nyūzen" 0 8 (charset japanese-jisx0208) 8 12 (charset latin-iso8859-4)) . "西入善")
    ("Ikuji"              . "生地")
    ("Kurobe"             . "黒部")
    ("Uozu"               . "魚津")
    ("Higashi-Namerikawa" . "東滑川")
    ("Namerikawa"         . "滑川")
    ("Mizuhashi"          . "水橋")
    ("Higashi-Toyama"     . "東富山")
    ("Toyama"             . "富山")
    ("Kureha"             . "呉羽")
    ("Kosugi"             . "小杉")
    (#("Ecchū-Daimon" 0 4 (charset japanese-jisx0208) 4 12 (charset latin-iso8859-4)) . "越中大門")
    ("Nishi-Takaoka"      . "西高岡")
    ("Fukuoka"            . "福岡")
    ("Isurugi"            . "石動")
    ("Kurikara"           . "倶利伽羅")
    ("Tsubata"            . "津幡")
    ("Morimoto"           . "森本")
    ("Higashi-Kanazawa"   . "東金沢")
    ("Kanazawa"           . "金沢")
    ("Nishi-Kanazawa"     . "西金沢")
    ("[JR] Nonoichi"      . "[JR] 野々市")
    (#("Mattō" 0 4 (charset japanese-jisx0208) 4 5 (charset latin-iso8859-4)) . "松任")
    ("Kaga-Kasama"        . "加賀笠間")
    ("Mikawa"             . "美川")
    ("Komaiko"            . "小舞子")
    ("Terai"              . "寺井")
    (#("Meihō" 0 4 (charset japanese-jisx0208) 4 5 (charset latin-iso8859-4)) . "明峰")
    ("Komatsu"            . "小松")
    ("Awazu"              . "粟津")
    ("Iburihashi"         . "動橋")
    ("Kaga-Onsen"         . "加賀温泉")
    (#("Daishōji" 0 5 (charset japanese-jisx0208) 5 8 (charset latin-iso8859-4)) . "大聖寺")
    ("Ushinoya"           . "牛ノ谷")
    ("Hosorogi"           . "細呂木")
    ("Awara-Onsen"        . "芦原温泉")
    ("Maruoka"            . "丸岡")
    ("Harue"              . "春江")
    ("Morita"             . "森田")
    ("Fukui"              . "福井")
    ("Tsuruga"            . "敦賀")
    ("Shin-Hikida"        . "新疋田")
    (#("Ōmi-Shiotsu" 0 11 (charset latin-iso8859-4)) . "近江塩津")
    ("Yogo"               . "余呉")
    ("Kinomoto"           . "木ノ本")
    ("Takatsuki"          . "高月")
    ("Kawake"             . "河毛")
    ("Torahime"           . "虎姫")
    ("Nagahama"           . "長浜")
    ("Tamura"             . "田村")
    ("Sakata"             . "坂田")
    (#("Tōkyō" 0 1 (charset japanese-jisx0208) 1 5 (charset latin-iso8859-4)) . "東京")
    ("Shinbashi"          . "新橋")
    ("Shinagawa"          . "品川")
    ("Kawasaki"           . "川崎")
    ("Yokohama"           . "横浜")
    ("Totsuka"            . "戸塚")
    (#("Ōfuna" 0 5 (charset latin-iso8859-4)) . "大船")
    ("Fujisawa"           . "藤沢")
    (#("Tsujidō" 0 6 (charset japanese-jisx0208) 6 7 (charset latin-iso8859-4)) . "辻堂")
    ("Chigasaki"          . "茅ヶ崎")
    ("Hiratsuka"          . "平塚")
    (#("Ōiso" 0 4 (charset latin-iso8859-4)) . "大磯")
    ("Ninomiya"           . "二宮")
    (#("Kōzu" 0 1 (charset japanese-jisx0208) 1 4 (charset latin-iso8859-4)) . "国府津")
    ("Kamonomiya"         . "鴨宮")
    ("Odawara"            . "小田原")
    ("Hayakawa"           . "早川")
    ("Nebukawa"           . "根府川")
    ("Manazuru"           . "真鶴")
    ("Yugawara"           . "湯河原")
    ("Atami"              . "熱海")
    ("Kan'nami"           . "函南")
    ("Mishima"            . "三島")
    ("Numazu"             . "沼津")
    ("Katahama"           . "片浜")
    ("Hara"               . "原")
    ("Higashi-Tagonoura"  . "東田子ノ浦")
    ("Yoshiwara"          . "吉原")
    ("Fuji"               . "富士")
    ("Fujikawa"           . "富士川")
    ("Shin-Kambara"       . "新蒲原")
    ("Kambara"            . "蒲原")
    ("Yui"                . "由比")
    ("Okitsu"             . "興津")
    ("Shimizu"            . "清水")
    ("Kusanagi"           . "草薙")
    ("Shizuoka"           . "静岡")
    ("Abekawa"            . "安倍川")
    ("Mochimune"          . "用宗")
    ("Yaizu"              . "焼津")
    ("Nishi-Yaizu"        . "西焼津")
    ("Fijieda"            . "藤枝")
    (#("Rokugō" 0 5 (charset japanese-jisx0208) 5 6 (charset latin-iso8859-4)) . "六合")
    ("Shimada"            . "島田")
    ("Kanaya"             . "金谷")
    ("Kikugawa"           . "菊川")
    ("Kakegawa"           . "掛川")
    ("Fukuroi"            . "袋井")
    ("Iwata"              . "磐田")
    (#("Toyodachō" 0 8 (charset japanese-jisx0208) 8 9 (charset latin-iso8859-4)) . "豊田町")
    (#("Tenryūgawa" 0 5 (charset japanese-jisx0208) 5 10 (charset latin-iso8859-4)) . "天竜川")
    ("Hamamatsu"          . "浜松")
    ("Takatsuka"          . "高塚")
    ("Maisaka"            . "舞阪")
    ("Bentenjima"         . "弁天島")
    ("Araimachi"          . "新居町")
    ("Wasizu"             . "鷲津")
    ("Shinjohara"         . "新所原")
    ("Futagawa"           . "二河")
    ("Toyohashi"          . "豊橋")
    ("Kanayama"           . "金山")
    (#("Otōbashi" 0 2 (charset japanese-jisx0208) 2 8 (charset latin-iso8859-4)) . "尾頭橋")
    ("Nagoya"             . "名古屋")
    ("Gifu"               . "岐阜")
    ("Samegai"            . "醒ヶ井")
    ("Maibara"            . "米原")
    ("Kusatsu"            . "草津")
    ("Yamashina"          . "山科")
    (#("Kyōto" 0 2 (charset japanese-jisx0208) 2 5 (charset latin-iso8859-4)) . "京都")
    (#("Ōsaka" 0 5 (charset latin-iso8859-4)) . "大阪")
    (#("Kōbe" 0 1 (charset japanese-jisx0208) 1 4 (charset latin-iso8859-4)) . "神戸")
    ("Himi"               . "氷見")
    ("Shimao"             . "島尾")
    ("Amaharashi"         . "雨晴")
    (#("Ecchū-Kokubu" 0 4 (charset japanese-jisx0208) 4 12 (charset latin-iso8859-4)) . "越中国分")
    ("Fushiki"            . "伏木")
    (#("Nōmachi" 0 1 (charset japanese-jisx0208) 1 7 (charset latin-iso8859-4)) . "能町")
    (#("Ecchū-Nakagawa" 0 4 (charset japanese-jisx0208) 4 14 (charset latin-iso8859-4)) . "越中中川")
    ("Takaoka"            . "高岡")
    ("Saigata"            . "犀潟")
    ("Kubiki"             . "くびき")
    (#("Ōike-Ikoinomori" 0 15 (charset latin-iso8859-4)) . "大池いこいの森")
    ("Uragawara"          . "うらがわら")
    (#("Mushigawaōsugi" 0 9 (charset japanese-jisx0208) 9 14 (charset latin-iso8859-4)) . "虫川大杉")
    (#("Hokuhoku-Ōshima" 0 9 (charset japanese-jisx0208) 9 15 (charset latin-iso8859-4)) . "ほくほく大島")
    ("Matsudai"           . "まつだい")
    (#("Nishi-Ōtsu" 0 6 (charset japanese-jisx0208) 6 10 (charset latin-iso8859-4)) . "西大津")))

(provide 'rail-table-semi)
