;; -*- coding: ctext; -*-

(defvar rail-flim-codename-alist
  '(("T-Dòji"               . "$(BEl;{(B")-A
    ("Kamitobaguchi"      . "$(B>eD;1)8}(B")
    ("Fushimi"            . "$(BIz8+(B")
    ("Kintetsu-Tambabashi" . "$(B6aE4C0GH66(B")
    ("Momoyama-Gory-Dòmae"  . "$(BEm;38fNMA0(B")-A
    ("Mukaijima"          . "$(B8~Eg(B")
    ("Ogura"              . "$(B>.AR(B")
    ("Iseda"              . "$(B0K@*ED(B")
    ("-DÒkubo"              . "$(BBg5WJ](B")-A
    ("Kutsukawa"          . "$(B5WDE@n(B")
    ("Terada"             . "$(B;{ED(B")
    ("Tonosh-Dò"            . "$(BIYLnAq(B")-A
    ("Shin-Tanabe"        . "$(B?7EDJU(B")
    ("K-Dòdo"               . "$(B6=8M(B")-A
    ("Miyamaki"           . "$(B;0;3LZ(B")
    ("Kintetsu-Miyazu"    . "$(B6aE45\DE(B")
    ("Komada"             . "$(B9}ED(B")
    ("Shin-H-Dòsono"        . "$(B?7=K1`(B")-A
    ("Kizugawadai"        . "$(BLZDE@nBf(B")
    ("Yamadagawa"         . "$(B;3ED@n(B")
    ("Takanohara"         . "$(B9b$N86(B")
    ("Heij-Dò"              . "$(BJ?>k(B")-A
    ("Saidaiji"           . "$(B@>Bg;{(B")
    ("Amagatsuji"         . "$(BFt%vDT(B")
    ("Nishinoky-Dò"         . "$(B@>$N5~(B")-A
    ("Kintetsu-K-Dòriyama"  . "$(B6aE474;3(B")-A
    ("Tsutsui"            . "$(BE{0f(B")
    ("Family-K-Dòenmae"     . "$(B%U%!%_%j!<8x1`A0(B")-A
    ("Y-Dþzaki"             . "$(B7k:j(B")-A
    ("Iwami"              . "$(B@P8+(B")
    ("Tawaramoto"         . "$(BED86K\(B")
    ("Kasanui"            . "$(B3^K%(B")
    ("Ninokuchi"          . "$(B?7%N8}(B")
    ("Yagi"               . "$(BH,LZ(B")
    ("Yagi-Nishiguchi"    . "$(BH,LZ@>8}(B")
    ("Unebigory-Dòmae"      . "$(B@&K58fNMA0(B")-A
    ("Kashiharajingu-mae" . "$(B3`86?@5\A0(B")
    ("Demachiyanagi"      . "$(B=PD.Lx(B")
    ("Keihan-Marutamachi" . "$(B5~:e4]B@D.(B")
    ("Sanj-Dò"              . "$(B;0>r(B")-A
    ("Keihan-Shij-Dò"       . "$(B5~:e;M>r(B")-A
    ("Keihan-Goj-Dò"        . "$(B5~:e8^>r(B")-A
    ("Shichij-Dò"           . "$(B<7>r(B")-A
    ("Tobakaid-Dò"          . "$(BD;1)39F;(B")-A
    ("Fushimiinari"       . "$(BIz8+0p2Y(B")
    ("Fukakusa"           . "$(B?<Ap(B")
    ("Fujinomori"         . "$(BF#?9(B")
    ("Sumizome"           . "$(BKO@w(B")
    ("Tambabashi"         . "$(BC0GH66(B")
    ("Fushimimomoyama"    . "$(BIz8+Em;3(B")
    ("Ch-Dþshojima"         . "$(BCf=qEg(B")-A
    ("Yodo"               . "$(BMd(B")
    ("Yawatashi"          . "$(BH,H(;T(B")
    ("Hashimoto"          . "$(B66K\(B")
    ("Kuzuha"             . "$(B>@MU(B")
    ("Makino"             . "$(BKRLn(B")
    ("Goten-yama"         . "$(B8fEB;3(B")
    ("Hirakatashi"        . "$(BKgJ};T(B")
    ("Hirakatak-Dòen"       . "$(BKgJ}8x1`(B")-A
    ("K-Dòzenji"            . "$(B8wA1;{(B")-A
    ("K-Dòrien"             . "$(B9aN$1`(B")-A
    ("Neyagawashi"        . "$(B?220@n;T(B")
    ("Kayashima"          . "$(B3~Eg(B")
    ("-DÒwada"              . "$(BBgOBED(B")-A
    ("Furukawabashi"      . "$(B8E@n66(B")
    ("Kadomashi"          . "$(BLg??;T(B")
    ("Nishisans-Dò"         . "$(B@>;0Aq(B")-A
    ("Moriguchishi"       . "$(B<i8};T(B")
    ("Doi"                . "$(BEZ5o(B")
    ("Takii"              . "$(BBl0f(B")
    ("Sembayashi"         . "$(B@iNS(B")
    ("Morish-Dòji"          . "$(B?9>.O)(B")-A
    ("Sekime"             . "$(B4XL\(B")
    ("Noe"                . "$(BLn9>(B")
    ("Ky-Dòbashi"           . "$(B5~66(B")-A
    ("Temmabashi"         . "$(BE7K~66(B")
    ("Kitahama"           . "$(BKLIM(B")
    ("Yodoyabashi"        . "$(BMd2066(B")
    ("Takeda"             . "$(BC]ED(B")
    ("Kuinabashi"         . "$(B$/$$$J66(B")
    ("J-Dþjò"               . "$(B==>r(B")-A
    ("Kuj-Dò"               . "$(B6e>r(B")-A
    ("Ky-Dòto"              . "$(B5~ET(B")-A
    ("Goj-Dò"               . "$(B8^>r(B")-A
    ("Shij-Dò"              . "$(B;M>r(B")-A
    ("Karasuma Oike"      . "$(B1(4]8fCS(B")
    ("Marutamach"         . "$(B4]B@D.(B")
    ("Imadegawa"          . "$(B:#=P@n(B")
    ("Kuramaguchi"        . "$(B0HGO8}(B")
    ("Kita-Dòji"            . "$(BKLBgO)(B")-A
    ("Kitayama"           . "$(BKL;3(B")
    ("Matugasaki"         . "$(B>>%v:j(B")
    ("Kokusaikaikan"      . "$(B9q:]2q4[(B")
    ("[JR] Ky-Dòto"         . "$(B5~ET(B")-A
    ("T-Dòfukuji"           . "$(BElJ!;{(B")-A
    ("Inari"              . "$(B0p2Y(B")
    ("JR Fujinomori "     . "JR $(BF#?9(B")
    ("Momoyama"           . "$(BEm;3(B")
    ("Rokujiz-Dò"           . "$(BO;COB"(B")-A
    ("Kohata"             . "$(BLZH((B")
    ("-DÒbaku"              . "$(B2+]!(B")-A
    ("Uji"                . "$(B1'<#(B")
    ("Shinden"            . "$(B?7ED(B")
    ("J-Dòyò"               . "$(B>kM[(B")-A
    ("Nagaike"            . "$(BD9CS(B")
    ("Yamashiro-Aodani"   . "$(B;3>k@DC+(B")
    ("Yamashiro-Taga"     . "$(B;3>kB?2l(B")
    ("Tamamizu"           . "$(B6L?e(B")
    ("Tanakura"           . "$(BC*AR(B")
    ("Kamikoma"           . "$(B>e9}(B")
    ("Kidu"               . "$(BLZDE(B")
    ("Shin-H-Dòryþji"       . "$(B?7K!N4;{(B")-A
    ("Ando"               . "$(B0BEH(B")
    ("Nukatabe"           . "$(B3[EDIt(B")
    ("Hirahata"           . "$(BJ?C<(B")
    ("Shin-Terai"         . "$(B?7;{0f(B")
    ("Tameike"            . "$(BN/CS(B")
    ("Kaga-Fukuoka"       . "$(B2C2lJ!2,(B")
    ("Nakanosh-Dò"          . "$(BCf%N>1(B")-A
    ("Gokend-Dò"            . "$(B8^4VF2(B")-A
    ("Terai-Nishiguchi"   . "$(B;{0f@>8}(B")
    ("Jid-Dòsha-Renraku"    . "$(B<+F0<VO"Mm(B")-A
    ("Hon-Terai"          . "$(BK\;{0f(B")
    ("Suenobuushijima"    . "$(BKv?.5mEg(B")
    ("Kaga-Sano"          . "$(B2C2l:4Ln(B")
    ("Yunotani-Ishiko"    . "$(BErC+@P;R(B")
    ("Tokuhisa"           . "$(BFA5W(B")
    ("Kami-Kaihatsu"      . "$(B>e3+H/(B")
    ("Tatsunokuchi"       . "$(BC$8}(B")
    ("Raimaru"            . "$(BMh4](B")
    ("Higama"             . "$(B2P3x(B")
    ("Iwauchi"            . "$(B4dFb(B")
    ("Mitsukuchi"         . "$(B;08}(B")
    ("Miyatake"           . "$(B5\C](B")
    ("Todashino"          . "$(BEtBf:{(B")
    ("Iwamoto"            . "$(B4dK\(B")
    ("Tenguyama"          . "$(BE76i;3(B")
    ("Hon-Tsurugi"        . "$(BK\DaMh(B")
    ("Tsurugi"            . "$(BDaMh(B")
    ("-DÒsaka-Abenobashi"   . "$(BBg:e0$ItLn66(B")-A
    ("Koboreguchi"        . "$(B2OKY8}(B")
    ("Kita-tanabe"        . "$(BKLEDJU(B")
    ("Imagawa"            . "$(B:#@n(B")
    ("Harinakano"         . "$(B?KCfLn(B")
    ("Yata"               . "$(BLpED(B")
    ("Kawachi-Amami"      . "$(B2OFbE7H~(B")
    ("Nunose"             . "$(BI[G&(B")
    ("Takaminosato"       . "$(B9b8+%NN$(B")
    ("Kawachi-Matsubara"  . "$(B2OFb>>86(B")
    ("Eganosh-Dò"           . "$(B7C2f%NAq(B")-A
    ("Takawashi"          . "$(B9bOI(B")
    ("Fujiidera"          . "$(BF#0f;{(B")
    ("Hajinosato"         . "$(BEZ;U$NN$(B")
    ("D-Dòmyòji"            . "$(BF;L@;{(B")-A
    ("Furuichi"           . "$(B8E;T(B")
    ("Komagatani"         . "$(B6p%vC+(B")
    ("Kaminotaishi"       . "$(B>e%NB@;R(B")
    ("Nij-Dòsan"            . "$(BFs>e;3(B")-A
    ("Nij-Dòjinjaguchi"     . "$(BFs>e?@<R8}(B")-A
    ("Taimadera"          . "$(BEvKc;{(B")
    ("Iwaki"              . "$(BHX>k(B")
    ("Shakudo"            . "$(B<\EZ(B")
    ("Takadashi"          . "$(B9bED;T(B")
    ("Ukiana"             . "$(BIb9&(B")
    ("B-Dòjò"               . "$(BK7>k(B")-A
    ("Kashiharajing-Dþ-Nisiguchi" . "$(B3`86?@5\@>8}(B")-A
    ("Kashiharajing-Dþmae"  . "$(B3`86?@5\A0(B")-A
    ("Okadera"            . "$(B2,;{(B")
    ("Asuka"              . "$(BHtD;(B")
    ("Tsubosakayama"      . "$(BTd:e;3(B")
    ("Ichio"              . "$(B;THx(B")
    ("Kuzu"               . "$(B3k(B")
    ("Yoshinoguchi"       . "$(B5HLn8}(B")
    ("Kusurimizu"         . "$(BLt?e(B")
    ("Fukugami"           . "$(BJ!?@(B")
    ("-DÒada"               . "$(BBg0$B@(B")-A
    ("Shimoichiguchi"     . "$(B2<;T8}(B")
    ("Koshibe"            . "$(B1[It(B")
    ("Muda"               . "$(BO;ED(B")
    ("Yamato-Kamiichi"    . "$(BBgOB>e;T(B")
    ("Yoshinojing-Dþ"       . "$(B5HLn?@5\(B")-A
    ("Yoshino"            . "$(B5HLn(B")))

(provide 'rail-table-flim)
